{% set name = "cp2k" %}
{% set version = "8.2.0" %}

# Define build matrix for MPI vs. non-mpi
# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}
{% set build = 0 %}
{% if mpi == 'nompi' %}
# prioritize 'nompi' variant via build number
{% set build = build + 1000 %}
{% endif %}

{% set build_string = "py{}_{}_{}".format(environ.get('CONDA_PY', ''), mpi, build) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version[:-2] }}.tar.bz2
  sha256: 2e24768720efed1a5a4a58e83e2aca502cd8b95544c21695eb0de71ed652f20a
  patches:
    - macosxtest.patch  # [osx]

build:
  number: {{ build }}
  skip: true  # [win]
  string: {{ build_string }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - autoconf
    - automake
    - cmake
    - libtool
    - python
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - scalapack  # [mpi != 'nompi']
    - libblas  # [osx]
    - openblas * *openmp*  # [linux]
    - liblapack
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - libxsmm
    - fftw
    - spglib
    - libxc >=5.1
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - scalapack  # [mpi != 'nompi']
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    - libblas * *openblas  # [linux]
    - openblas * *openmp*  # [linux]

test:
  commands:
    # note: regtests are running at "build" stage; this is just a smoke test
    - cp2k.ssmp --help  # [mpi == 'nompi']
    - mpiexec --bind-to none -mca plm isolated cp2k.psmp --help   # [mpi != 'nompi']


about:
  home: https://www.cp2k.org
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Quantum chemistry and solid state physics software package

  description: |
    CP2K is a quantum chemistry and solid state physics software package 
    that can perform atomistic simulations of solid state, liquid, 
    molecular, periodic, material, crystal, and biological systems. 
  doc_url: https://manual.cp2k.org
  dev_url: https://github.com/cp2k/cp2k

extra:
  recipe-maintainers:
    - jan-janssen
    - oschuett
    - ltalirz
