{% set name = "cp2k" %}
{% set version = "8.2.0" %}

# Define build matrix for MPI vs. non-mpi
# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}
{% set build = 2 %}
{% if mpi == 'nompi' %}
# prioritize 'nompi' variant via build number
{% set build = build + 1000 %}
{% endif %}

{% set build_string = "py{}_{}_{}".format(environ.get('CONDA_PY', ''), mpi, build) %}

package:
  name: {{ name|lower }}-pkgs
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version[:-2] }}.tar.bz2
  sha256: 2e24768720efed1a5a4a58e83e2aca502cd8b95544c21695eb0de71ed652f20a
  patches:
    - macosxtest.patch  # [osx]
    # remove in release following cp2k 8.2
    - sirius.patch

build:
  number: {{ build }}
  # osx build skipped until futher notice:
  # - nompi: osx issue introduced in 8.1, fixed in future 8.2
  # - openmpi: runtime failures during test suite
  skip: true  # [not linux]
  string: {{ build_string }}

outputs: 
  - name: {{ name|lower }}
    build:
      skip: true  # [not linux]
      string: {{ build_string }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - make
        - autoconf
        - automake
        - cmake
        - libtool
        - python
      host:
        - {{ mpi }}  # [mpi != 'nompi']
        - scalapack  # [mpi != 'nompi']
        - libblas  # [osx]
        - openblas * *openmp*  # [linux]
        - liblapack
        - llvm-openmp  # [osx]
        - libgomp  # [linux]
        - libxsmm
        - fftw
        - spglib
        - libxc >=5.1
        - sirius  # [mpi != 'nompi']
      run:
        - {{ mpi }}  # [mpi != 'nompi']
        - scalapack  # [mpi != 'nompi']
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
        - libblas * *openblas  # [linux]
        - openblas * *openmp*  # [linux]
    test:
      commands:
        # note: regtests are running at the "build" stage; this is just a smoke test
        - cp2k.ssmp --help  # [mpi == 'nompi']
        - mpiexec --bind-to none -mca plm isolated cp2k.psmp --help   # [mpi != 'nompi']

  - name: {{ name|lower }}-potentials
    build:
      skip: true  # [not linux]
      script: mkdir ${PREFIX}/share/cp2k; cp -r data/*  ${PREFIX}/share/cp2k
    requirements:
      host:
      run:
    test:
      commands:
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/ho.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/znzn.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/ss.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/ph.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/hn.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/sp.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/znc.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/po.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/sc.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/pn.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/hh.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/zns.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/ozn.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/szn.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/oh.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/hzn.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/ch.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/no.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/nn.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/on.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/nzn.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/oo.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/cn.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/nh.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/co.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/ns.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/cc.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/np.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/oc.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/cs.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/op.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/nc.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/oo_modi.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/cp.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/os.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/znh.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/scc_parameter
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/oh_modi.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/ho_modi.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/hp.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/czn.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/pc.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/so.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/sn.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/hs.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/znn.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/uff_table
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/pp.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/zno.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/hc.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/ps.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/scc/sh.spl
        - test -f ${PREFIX}/share/cp2k/DFTB/uff_table
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/osi-d
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/pp
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/hb
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/kcl_exp
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/csi
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/clk_exp
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/bb
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/nn
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/smo
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/no
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/nh
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/bc
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/sio
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/nbs
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/sih
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/cn
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/sisi
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/nana_exp
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/fc
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/oc
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/ch
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/co
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/cf
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/sin
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/scn
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/mos
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/licl_exp
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/nsi
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/clli_exp
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/clna_exp
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/ss
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/nbnb
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/sio-d
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/nacl_exp
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/bh
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/nc
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/momo
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/csc
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/snb
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/clcl_exp
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/hh
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/osi
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/bn
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/nb
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/sisi-d
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/lili_exp
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/scsc
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/sih-d
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/oo
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/cc
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/nonscc_parameter
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/oh
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/hh0
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/ff
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/fh
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/scc
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/sic
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/cb
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/on
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/kk_exp
        - test -f ${PREFIX}/share/cp2k/DFTB/nonscc/nsc
        - test -f ${PREFIX}/share/cp2k/BASIS_ADMM_MOLOPT
        - test -f ${PREFIX}/share/cp2k/GTH_POTENTIALS
        - test -f ${PREFIX}/share/cp2k/MM_POTENTIAL
        - test -f ${PREFIX}/share/cp2k/BASIS_MOLOPT_AcPP1
        - test -f ${PREFIX}/share/cp2k/t_c_g.dat
        - test -f ${PREFIX}/share/cp2k/BASIS_MOLOPT_UCL
        - test -f ${PREFIX}/share/cp2k/GTH_BASIS_SETS
        - test -f ${PREFIX}/share/cp2k/HF_POTENTIALS
        - test -f ${PREFIX}/share/cp2k/BASIS_ccGRB_UZH
        - test -f ${PREFIX}/share/cp2k/BASIS_ADMM_UZH
        - test -f ${PREFIX}/share/cp2k/rVV10_kernel_table.dat
        - test -f ${PREFIX}/share/cp2k/BASIS_MOLOPT_UZH
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-7/weights.008.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-7/weights.001.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-7/input.nn
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-7/scaling.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-8/weights.008.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-8/weights.001.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-8/input.nn
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-8/scaling.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-6/weights.008.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-6/weights.001.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-6/input.nn
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-6/scaling.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-1/weights.008.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-1/weights.001.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-1/input.nn
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-1/scaling.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-4/weights.008.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-4/weights.001.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-4/input.nn
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-4/scaling.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-3/weights.008.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-3/weights.001.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-3/input.nn
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-3/scaling.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-2/weights.008.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-2/weights.001.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-2/input.nn
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-2/scaling.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-5/weights.008.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-5/weights.001.data
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-5/input.nn
        - test -f ${PREFIX}/share/cp2k/NNP/bulkH2O-jcp2020-cnnp/nnp-5/scaling.data
        - test -f ${PREFIX}/share/cp2k/ALL_POTENTIALS
        - test -f ${PREFIX}/share/cp2k/BASIS_pob
        - test -f ${PREFIX}/share/cp2k/ALL_BASIS_SETS
        - test -f ${PREFIX}/share/cp2k/BASIS_MOLOPT_LnPP1
        - test -f ${PREFIX}/share/cp2k/EMSL_BASIS_SETS
        - test -f ${PREFIX}/share/cp2k/ECP_POTENTIALS
        - test -f ${PREFIX}/share/cp2k/BASIS_def2_QZVP_RI_ALL
        - test -f ${PREFIX}/share/cp2k/BASIS_MOLOPT
        - test -f ${PREFIX}/share/cp2k/xc_section/vdW-DF-cx.sec
        - test -f ${PREFIX}/share/cp2k/xc_section/vdW-DF-cx0p.sec
        - test -f ${PREFIX}/share/cp2k/xc_section/vdW-DF-optPBE.sec
        - test -f ${PREFIX}/share/cp2k/xc_section/HF-3c.sec
        - test -f ${PREFIX}/share/cp2k/xc_section/vdW-DF-optB88.sec
        - test -f ${PREFIX}/share/cp2k/xc_section/vdW-DF2-b86r.sec
        - test -f ${PREFIX}/share/cp2k/xc_section/vdW-DF2.sec
        - test -f ${PREFIX}/share/cp2k/xc_section/vdW-DF1.sec
        - test -f ${PREFIX}/share/cp2k/xc_section/vdW-DF1-C09.sec
        - test -f ${PREFIX}/share/cp2k/xc_section/PBE.sec
        - test -f ${PREFIX}/share/cp2k/BASIS_SET
        - test -f ${PREFIX}/share/cp2k/POTENTIAL
        - test -f ${PREFIX}/share/cp2k/vdW_kernel_table.dat
        - test -f ${PREFIX}/share/cp2k/LnPP1_POTENTIALS
        - test -f ${PREFIX}/share/cp2k/BASIS_RI_cc-TZ
        - test -f ${PREFIX}/share/cp2k/POTENTIAL_UZH
        - test -f ${PREFIX}/share/cp2k/AcPP1_POTENTIALS
        - test -f ${PREFIX}/share/cp2k/nm12_parameters.xml
        - test -f ${PREFIX}/share/cp2k/BASIS_ZIJLSTRA
        - test -f ${PREFIX}/share/cp2k/t_sh_p_s_c.dat
        - test -f ${PREFIX}/share/cp2k/xTB_parameters
        - test -f ${PREFIX}/share/cp2k/BASIS_MINIX
        - test -f ${PREFIX}/share/cp2k/BASIS_ADMM
        - test -f ${PREFIX}/share/cp2k/HFX_BASIS
        - test -f ${PREFIX}/share/cp2k/dftd3.dat
        - test -f ${PREFIX}/share/cp2k/NLCC_POTENTIALS
        - test -f ${PREFIX}/share/cp2k/BASIS_LRIGPW_AUXMOLOPT

about:
  home: https://www.cp2k.org
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Quantum chemistry and solid state physics software package

  description: |
    CP2K is a quantum chemistry and solid state physics software package 
    that can perform atomistic simulations of solid state, liquid, 
    molecular, periodic, material, crystal, and biological systems. 
  doc_url: https://manual.cp2k.org
  dev_url: https://github.com/cp2k/cp2k

extra:
  recipe-maintainers:
    - jan-janssen
    - oschuett
    - ltalirz
