{% set name = "cp2k" %}
{% set version = "7.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cp2k/cp2k/releases/download/v{{ version }}/cp2k-{{ version[:-2] }}.tar.bz2
  sha256: e244f76d7e1e98da7e4e4b2e6cefb723fa1205cfae4f94739413be74952e8b4e

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - autoconf
    - automake
    - cmake 
    - libtool
    - python 
  host:
    - libblas
    - liblapack

test:
  commands:
    - cp2k.sopt --help

about:
  home: https://www.cp2k.org
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Quantum chemistry and solid state physics software package'

  description: |
    CP2K is a quantum chemistry and solid state physics software package 
    that can perform atomistic simulations of solid state, liquid, 
    molecular, periodic, material, crystal, and biological systems. 
  doc_url: https://manual.cp2k.org
  dev_url: https://github.com/cp2k/cp2k

extra:
  recipe-maintainers:
    - jan-janssen
    - oschuett
