{% set name = "cp2k" %}
{% set version = "2026.1" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  - url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.bz2
    sha256: 4364c74bcffaa474bc234e11686b09550e4d06932acf2147a341e4f7679dd88e

build:
  number: 2
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - cmake >=3.27
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - ninja >=1.13
    - openmpi-mpifort >=5.0.8
    - pkgconfig >=1.6
    - python >=3.11
  host:
    - dbcsr >=2.9.0
    - "elpa >=2024.05.001 *openmpi_*"
    - "fftw >=3.3.10 *openmpi_*"
    - libint >=2.6.0
    - libint-fortran-devel >=2.6.0
    - "libxc >=7.0.0 *cpu_*"
    - "openblas >=0.3.30 *openmp_*"
    - openmpi >=5.0.8
    - scalapack >=2.2.0
    - spglib >=2.5.0
  run:
    - "openblas >=0.3.30 *openmp_*"

test:
  commands:
    - cp2k -v
    - cp2k -h

about:
  home: https://www.cp2k.org
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Quantum chemistry and solid state physics software package

  description: |
    CP2K is a quantum chemistry and solid state physics software package 
    that can perform atomistic simulations of solid state, liquid, 
    molecular, periodic, material, crystal, and biological systems. 
  doc_url: https://manual.cp2k.org
  dev_url: https://github.com/cp2k/cp2k

extra:
  recipe-maintainers:
    - jan-janssen
    - oschuett
    - ltalirz
    - mkrack
