{% set name = "cp2k" %}
{% set version = "8.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version[:-2] }}.tar.bz2
  sha256: ddf050e34300afa28bdf846f7b391f7e2489b44040535f78d516d9789ff7d010
  patches:
    - regtest.patch
    - macosxtest.patch  # [osx]

build:
  number: 0
  skip: true  # [not (linux or osx)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - make
    - autoconf
    - automake
    - cmake
    - libtool
    - python
  host:
    - libblas
    - liblapack

test:
  commands:
    - cp2k.ssmp --help

about:
  home: https://www.cp2k.org
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Quantum chemistry and solid state physics software package

  description: |
    CP2K is a quantum chemistry and solid state physics software package 
    that can perform atomistic simulations of solid state, liquid, 
    molecular, periodic, material, crystal, and biological systems. 
  doc_url: https://manual.cp2k.org
  dev_url: https://github.com/cp2k/cp2k

extra:
  recipe-maintainers:
    - jan-janssen
    - oschuett
    - ltalirz
