schema_version: 1

context:
  name: cp2k
  version: "2026.1"
  mpi_prefix: "mpi_${{ mpi }}"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/${{ name }}/${{ name }}/releases/download/v${{ version }}/${{ name }}-${{ version }}.tar.bz2
    sha256: 4364c74bcffaa474bc234e11686b09550e4d06932acf2147a341e4f7679dd88e

build:
  number: 11
  script: build.sh
  string: mpi_${{ mpi }}_h${{ hash }}_${{ build_number }}
  skip:
    - if: aarch64 or osx or win
      then: true

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("fortran") }}
    - ${{ mpi }}
    - cmake >=3.27
    - ninja >=1.13
    - pkg-config
  host:
    - ${{ mpi }}
    - "dbcsr >=2.9 *${{ mpi_prefix }}_*"
    - "fftw * *${{ mpi_prefix }}_*"
    - hdf5
    - libint
    - libint-fortran-devel
    - "libtorch >=2.7.1 *cpu_*"
    - "libxc >=7.0.0 *cpu_*"
    - libxsmm
    - "openblas * *openmp_*"
    - "plumed >=2.9.2 *${{ mpi_prefix }}_*"
    - scalapack
    - "sirius * *${{ mpi_prefix }}_*"
    - "spfft * ${{ mpi_prefix }}_*"
    - "spla * ${{ mpi_prefix }}_*"
    - spglib
#   - tblite
    - trexio
    - if: mpi == "openmpi"
      then:
        - "elpa >=2024.05.001 *${{ mpi_prefix }}_*"
  run:
    - ${{ mpi }}
    - "openblas * *openmp_*"
    - "plumed >=2.9.2 *${{ mpi_prefix }}_*"
    - "sirius * *${{ mpi_prefix }}_*"
    - "spfft * ${{ mpi_prefix }}_*"
    - "spla * ${{ mpi_prefix }}_*"

tests:
  # 1. Verify that the files exist in the bin directory
  - package_contents:
      bin:
        - cp2k.psmp
        - cp2k.popt
        - cp2k
  # 2. Run commands to verify they execute successfully
  - script:
      - if: linux
        then: ldd ${PREFIX}/bin/cp2k.psmp
      - ${PREFIX}/bin/cp2k.psmp -v
      - ${PREFIX}/bin/cp2k.popt -h

about:
  homepage: https://www.cp2k.org
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Quantum chemistry and solid state physics software package
  description: |
    CP2K is a quantum chemistry and solid state physics software package
    that can perform atomistic simulations of solid state, liquid,
    molecular, periodic, material, crystal, and biological systems.
  documentation: https://manual.cp2k.org
  repository: https://github.com/cp2k/cp2k

extra:
  recipe-maintainers:
    - jan-janssen
    - oschuett
    - ltalirz
    - mkrack
