travis:
  secure:
    BINSTAR_TOKEN: rsqQHhsB4tDPlZx5vKqDgCldY5YoqPadnmjHE/PNDh+5fJJqJBfZH6iciVQGLnyQOeH13HEvUu3Xb7/6cJPAcSWtrQVEqu3OUtEmKgLzvR+H7jbcMwbOqVQy8Xt1wYzAZ7H3JNCA7yrHgBCkPzzxKY9oP4104NUHslqLIftU6RQ5t4I8x4XrZqvBPiBqO8PpHHqWnbYUU9eTgDfwk2vZv/QzzMe9Bx4X+I+zOCcRC1yOcOyDev0gkqN2d3cRc5kFcbS9wPge73594aYqduJuctC/jzA/c/SOMgi5xAq/Q4IiuzhaDQg34qjs7XBtO2OKD1+9nJDMOqilbjM/rBR1+JgAf8yOarKfdIs5PWBxUEYJ6TVL987OlHRhsshb8vguEUj2fFPHADYRTci8L8M1YSxMsBDT6LLQcUIk0vj245qb00XbKJF98mzKusjcSN+LOuhrAMgtRNXPzdD/CXTuXisXJaTaaWNK9Fid9Vf7mlWzCJ0FuKzlH51a3FihjRtzOlYLo2Cz0lAZNA2rEjpmf4RPMaJ9vCCZmplZ13sLJqbR8Zt9iZP4xoC/F20CgldWJe3ffRP3xZwbK44mrIVLs5CCjSiU+kub9caTzFA4SVSbKs4wOegzt5VMIlplJvbCgB8ZMuTNxwkf8oFUqbZAkhCBjtY1AfkQL5/YMTU6ZsA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
